'use strict'; // code generated by pbf v3.0.5

// Location ========================================

var Location = exports.Location = {};

Location.read = function (pbf, end) {
    return pbf.readFields(Location._readField, {lat: 0, lon: 0, unknown3: 0, unknown4: 0, unknown5: 0, unknown6: 0, unknown11: 0, unknown12: 0}, end);
};
Location._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.lat = pbf.readVarint(true);
    else if (tag === 2) obj.lon = pbf.readVarint(true);
    else if (tag === 3) obj.unknown3 = pbf.readVarint(true);
    else if (tag === 4) obj.unknown4 = pbf.readVarint(true);
    else if (tag === 5) obj.unknown5 = pbf.readVarint(true);
    else if (tag === 6) obj.unknown6 = pbf.readVarint(true);
    else if (tag === 11) obj.unknown11 = pbf.readVarint(true);
    else if (tag === 12) obj.unknown12 = pbf.readVarint(true);
};
Location.write = function (obj, pbf) {
    if (obj.lat != null) pbf.writeVarintField(1, obj.lat);
    if (obj.lon != null) pbf.writeVarintField(2, obj.lon);
    if (obj.unknown3 != null) pbf.writeVarintField(3, obj.unknown3);
    if (obj.unknown4 != null) pbf.writeVarintField(4, obj.unknown4);
    if (obj.unknown5 != null) pbf.writeVarintField(5, obj.unknown5);
    if (obj.unknown6 != null) pbf.writeVarintField(6, obj.unknown6);
    if (obj.unknown11 != null) pbf.writeVarintField(11, obj.unknown11);
    if (obj.unknown12 != null) pbf.writeVarintField(12, obj.unknown12);
};

// Device ========================================

var Device = exports.Device = {};

Device.read = function (pbf, end) {
    return pbf.readFields(Device._readField, {bssid: "", location: null, channel: 0}, end);
};
Device._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.bssid = pbf.readString();
    else if (tag === 2) obj.location = Location.read(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 21) obj.channel = pbf.readVarint();
};
Device.write = function (obj, pbf) {
    if (obj.bssid != null) pbf.writeStringField(1, obj.bssid);
    if (obj.location != null) pbf.writeMessage(2, Location.write, obj.location);
    if (obj.channel != null) pbf.writeVarintField(21, obj.channel);
};

// Request ========================================

var Request = exports.Request = {};

Request.read = function (pbf, end) {
    return pbf.readFields(Request._readField, {devices: [], unknown: 0, results: 0}, end);
};
Request._readField = function (tag, obj, pbf) {
    if (tag === 2) obj.devices.push(Device.read(pbf, pbf.readVarint() + pbf.pos));
    else if (tag === 3) obj.unknown = pbf.readVarint();
    else if (tag === 4) obj.results = pbf.readVarint();
};
Request.write = function (obj, pbf) {
    if (obj.devices != null) for (var i = 0; i < obj.devices.length; i++) pbf.writeMessage(2, Device.write, obj.devices[i]);
    if (obj.unknown != null) pbf.writeVarintField(3, obj.unknown);
    if (obj.results != null) pbf.writeVarintField(4, obj.results);
};

// Response ========================================

var Response = exports.Response = {};

Response.read = function (pbf, end) {
    return pbf.readFields(Response._readField, {devices: []}, end);
};
Response._readField = function (tag, obj, pbf) {
    if (tag === 2) obj.devices.push(Device.read(pbf, pbf.readVarint() + pbf.pos));
};
Response.write = function (obj, pbf) {
    if (obj.devices) for (var i = 0; i < obj.devices.length; i++) pbf.writeMessage(2, Device.write, obj.devices[i]);
};
